server: 
  port: 8082
  
netty_server_port: 1111
not_require_user_authority_url: /admin/user/login,/admin/user/logout,/admin/user/get/public/key,/admin/uploadImg,/favicon.ico,/admin/template/data/receive,/admin/netty/test/message,/admin/netty/close/sms/cat,/admin/accept/extenal/data,/admin/file/list
  
  
upload_image: 
  path: E:/uploads  #
smscat: 
  serverPortName: COM3
  serverPortBound: 115200
  
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.199:3306/newdatasource?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 
    tomcat:
      max-active: 500
      max-idle: 10
      min-idle: 5
      initial-size: 5


#   上传服务器配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/newdatasource?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&validationQuery=SELECT 1
#    username: xiaozl
#    password: Sql@2019
    
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  http:
    multipart:
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false



