server: 
  port: 8081
  
netty_server_port: 1111
not_require_user_authority_url: /admin/user/login,/admin/user/logout,/admin/uploadImg
  
upload_image: 
  path: D:/uploads  #需要事先创建好文件目录
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/newdatasource?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 
    tomcat:
      max-active: 500
      max-idle: 10
      min-idle: 5
      initial-size: 5
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  http:
    multipart:
      max-file-size: 10MB



