server: 
  port: 8082

  
netty_server_port: 1111 #

http_netty_server_port: 1112

not_require_user_authority_url: /admin/user/login,/admin/user/loginApp,/admin/user/logout,/admin/user/get/public/key,/admin/uploadImg,/favicon.ico,/admin/template/data/receive,/admin/netty/test/message,/admin/netty/close/sms/cat,/admin/accept/extenal/data,/admin/file/list,/admin/user/getImage,/admin/downLogFile,/admin/export/excel,/admin/screen/display,/admin/screen/getPointInfo,/admin/line/list,/admin/screen/searchPoints,/admin/picture/create,/admin/picture/modify,/admin/picture/list,/admin/point/define/list,/admin/line/list,/admin/downLogFile,/admin/picture/delete,/admin/var/list,/admin/alarm/data/already/read,/admin/company/listTree,/admin/line/list,/admin/point/define/list,/admin/user/getVerifyCode,/admin/screen/queryBack,/admin/screen/searchPoints,/admin/alarm/data/list,/admin/user/resetPass,/admin/alarm/data/down/record,/admin/equipment/currentPointInfo,/admin/equipment/historyPointInfo,/admin/point/data/list,/admin/point/data/table,/admin/temperature/data/list,/admin/temperature/data/table,/admin/Partial/Discharge/table,/admin/Partial/Discharge/list
 

system_name: 长缆科技管理系统

  
upload_image: 
  path: E:/  #
smscat: 
  serverPortName: COM3
  serverPortBound: 115200
  
smscattype: 0
  
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/newdatasource?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&validationQuery=SELECT 1
#    username: root
#    password: 
    url: jdbc:mysql://192.168.33.30:3306/newdatasource?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&validationQuery=SELECT 1
    username: user1
    password: Mysql@2008
    tomcat:
      max-active: 500
      max-idle: 10
      min-idle: 5
      initial-size: 5


#   上传服务器配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/newdatasource?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&validationQuery=SELECT 1
#    username: xiaozl
#    password: Sql@2019
    
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
#  http:
#    multipart:
#      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false



